### ISSUE TITLE
BUG: missing optional scripts in runX/run1

### ISSUE THREAD

**Issue by pcmoore** [ddrown/chrony-graph#11]
Hi @ddrown, thanks for sharing these scripts.

While reading through the [README.md](https://github.com/ddrown/chrony-graph/blob/master/README.md) I saw that it makes reference to two scripts, run1/starttime and run1/custom-plot, which are not present in this repository.  Perhaps they fell victim to a missing `git add` command, or were removed at some point?  If these scripts are available it would be nice if they could be added to the repo.

Thanks!

**Comment by ddrown** [comment]
They are both optional scripts, which is why they were not included.

Here's an example run1/startime:
```
#!/bin/sh

NOW=`date +%s`
# 604800 seconds = 7 days
STARTIME=`expr $NOW - 604800`
# minimum start time in unix format from: env TZ=GMT date -d "May 23 04:33" +%s
MINTIME=1466213000

if [ $STARTIME -lt $MINTIME ]; then
  echo $MINTIME
else
  echo $STARTIME
fi
```

run1/custom-plot is just a place to generate other gnuplot graphs if you wanted to do something like compare multiple servers in the same image

**Comment by pcmoore** [comment]
I saw the other example scripts and figured there might be some basic/example scripts.  No worries.
